#pragma once

// make sure the method is METHOD_BUFFERED for in/out data
#define DRIVER_BUDDY_DEVICE 0x8000
#define IOCTL_DRIVER_BUDDY_WATCH_DRIVER CTL_CODE(DRIVER_BUDDY_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_BUDDY_UNWATCH_UNPATCH_DRIVER CTL_CODE(DRIVER_BUDDY_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DRIVER_BUDDY_DISABLE_SMAP CTL_CODE(DRIVER_BUDDY_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_BUDDY_ENABLE_SMAP CTL_CODE(DRIVER_BUDDY_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_BUDDY_EXECUTE CTL_CODE(DRIVER_BUDDY_DEVICE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DRIVER_BUDDY_INIT_SHARED_MEM CTL_CODE(DRIVER_BUDDY_DEVICE, 0x805, METHOD_NEITHER, FILE_ANY_ACCESS)

#define USER_ID L"BuddyUserEvent"
#define KERNEL_ID L"BuddyKernelEvent"
#define BUDDY_MEM_ID L"BuddySharedMem"

typedef struct DriverInfo DriverInfo;

struct DriverInfo
{
	PCWSTR driverName;
};

typedef enum BUDDY_CMD_
{
	BUDDY_CMD_EXECUTE,
	BUDDY_CMD_EXECUTE_COMPLETE,
} BUDDY_CMD;

typedef struct SharedMem
{
	BUDDY_CMD cmd;
	int		  length;
	char	  data[];
} BUDDY_SHMEM, *PBUDDY_SHMEM;
